version: "3.9"

services:
  health_server:
    build: .
    container_name: health_server
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health_check"]
      interval: 30s
      timeout: 2s
      retries: 3